
= Contest details

This contest is related to previous challenges from Chia Networks, but this
contest is not run by nor affiliated with them. It is merely being setup by a
fan of the math puzzle embedded in those contests.

== Contest Rules

The following are suggested rules, and will be finalized after some (hopefully
short) time to get some feedback from the community.

. Anyone may enter (explicitly including Chia employees), and winner(s) will be awarded prizes pledged by community donors.
. Contest period for entries ends on August 31th, 2020 at 00:00 UTC.
. Participants must:
.. Provide a publicly accessible git repo, which must contain:
... a python file: `entry.py` -- contains code of your algorithm which is compatible with testing by `run_trial.py`
... explanation of the algorithm should be supplied (either as comments in the code, or a separate document included in the git repo)
... a text file: `prize.txt` -- cryptocoin address(es) where prizes should be sent
... a `LICENSE` file, placing all source code and documentation in a submission related to the contest into the public domain, or released with an MIT or Apache 2.0 License.
.. Register an entry before the contest period ends by submitting a pull
request to this github repo which adds the following information
to `entry_registration.txt`:
... the git hash of the commit of your git repo to be considered for the contest entry
... publicly accessible url from which the git repository can be cloned after the contest period ends
.. [Optional] a contest entry can be registered without releasing your algorithm details until the contest period ends.
... Register as normal, but keep your git repo private, or just not pushed to the public server, until the contest period ends
... In this case, the repo should be made public within a day of the contest period ending.
. Tied scores will be resolved by whoever submitted first.
. An entry that calculates an incorrect answer during testing will be disqualified.
. An entry should out perform the provided example entries to be eligible for a prize.
. To resolve disputes, the person pledging a prize has final say on that prize.
What follows are suggestions for handling some situations:
.. Entries which are found to evade or directly manipulate the computation cost tracking will be invalidated.
.. If there are prizes for 2nd place or below, then duplicate entries or entries deemed as "substantially duplicate" of other entries will be invalidated except for the one submitted first.
. Participants may discuss, share, and collaborate on ideas however they choose.
. Contest test values will be generated by running
+
  $ ./create_test_file.py -s "$SECRET_SEED" -n 100 -b 2048 contest.txt
+
. Contest test seed `$SECRET_SEED` is precommitted by
+
  $ echo "$SECRET_SEED" | sha256sum
  efa47bb2d9c31d41c921c9102a1dc2d13a007e180bdce336152de8769b98e31b  -
+
. Contest entries will be scored by running (lowest total cost wins)

  $ ./run_trial.py -t contest.txt entry


== Current prize pledges

* user "PulledPork" pledges 2 ETH for first place, and I will not enter the contest for added fairness

If you would like to add to the community prize pool, please contact me on
keybase chat with the details and I'll add them here.

